export enum userDataActions {
  SET_USER_DATA = 'SET_USER_DATA',
  REMOVE_USER_DATA = 'REMOVE_USER_DATA',
  UPDATE_USER_DATA = 'UPDATE_USER_DATA',
}
export enum postsDataActions {
  LOAD_POSTS = 'LOAD_POSTS',
  ADD_POSTS = 'ADD_POSTS',
  DELETE_POST = 'DELETE_POST',
  CHANGE_POST = 'CHANGE_POST',
}
