export enum userDataActions {
  SET_USER_DATA = 'SET_USER_DATA',
  REMOVE_USER_DATA = 'REMOVE_USER_DATA',
  UPDATE_USER_DATA = 'UPDATE_USER_DATA',
}
export enum postsDataActions {
  LOAD_POSTS = 'LOAD_POSTS',
  ADD_POSTS = 'ADD_POSTS',
  DELETE_POST = 'DELETE_POST',
  CHANGE_POST = 'CHANGE_POST',
}
export enum studioDataActions {
  LAOD_VIDEOS = 'LAOD_VIDEOS',
  ADD_VIDEOS = 'ADD_VIDEOS',
  DELETE_VIDEOS = 'DELETE_VIDEOS',
  UPDATE_VIDEO_DATA = 'UPDATE_VIDEO_DATA',
}
